steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/point-app-api-server', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/point-app-api-server']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'point-app-api-server', '--image', 'gcr.io/$PROJECT_ID/point-app-api-server', '--platform', 'managed', '--region', 'asia-northeast1', '--allow-unauthenticated']